patches-source = "inotia00/revanced-patches"
rv-brand = "ReVanced eXtended"
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "module"
included-patches = "'Ambient mode control' 'Bypass URL redirects' 'Change live ring click action' 'Disable resuming Miniplayer on startup' 'Disable resuming Shorts on startup' 'Enable OPUS codec' 'Hide ads' 'Hook download actions' 'MaterialYou' 'Miniplayer' 'Open links externally' 'Remove background playback restrictions' 'Return YouTube Dislike' 'Return YouTube Username' 'Sanitize sharing links' 'Settings for YouTube' 'SponsorBlock'"
exclusive-patches = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music]
arch = "arm64-v8a"
build-mode = "module"
included-patches = "'Bitrate default value' 'Certificate spoof' 'Disable DRC audio' 'Disable dislike redirection' 'Disable music video in album' 'Enable OPUS codec' 'Enable landscape mode' 'Hide ads' 'Remove background playback restrictions' 'Return YouTube Dislike' 'Return YouTube Username' 'Sanitize sharing links' 'Settings for YouTube Music' 'SponsorBlock'"
exclusive-patches = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
